# Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime
from sklearn.model_selection import train_test_split

In [2]:
climatedata = pd.read_csv("C:/Users/v4run/Downloads/train.csv")

In [3]:
climatedata.head()

,Year_Factor,State_Factor,building_class,facility_type,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,...,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,id
0,1,State_1,Commercial,Grocery_store_or_food_market,61242.0,1942.0,11.0,2.4,36,50.5,...,14,0,0,0,1.0,1.0,1.0,NaN,248.682615,0
1,1,State_1,Commercial,Warehouse_Distribution_or_Shipping_center,274000.0,1955.0,45.0,1.8,36,50.5,...,14,0,0,0,1.0,NaN,1.0,12.0,26.500150,1
2,1,State_1,Commercial,Retail_Enclosed_mall,280025.0,1951.0,97.0,1.8,36,50.5,...,14,0,0,0,1.0,NaN,1.0,12.0,24.693619,2
3,1,State_1,Commercial,Education_Other_classroom,55325.0,1980.0,46.0,1.8,36,50.5,...,14,0,0,0,1.0,NaN,1.0,12.0,48.406926,3
4,1,State_1,Commercial,Warehouse_Nonrefrigerated,66000.0,1985.0,100.0,2.4,36,50.5,...,14,0,0,0,1.0,1.0,1.0,NaN,3.899395,4

In [4]:
climatedata.shape

(75757, 64)

In [5]:
climatedata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75757 entries, 0 to 75756
Data columns (total 64 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year_Factor                75757 non-null  int64
 1   State_Factor               75757 non-null  object
 2   building_class             75757 non-null  object
 3   facility_type              75757 non-null  object
 4   floor_area                 75757 non-null  float64
 5   year_built                 73920 non-null  float64
 6   energy_star_rating         49048 non-null  float64
 7   ELEVATION                  75757 non-null  float64
 8   january_min_temp           75757 non-null  int64
 9   january_avg_temp           75757 non-null  float64
 10  january_max_temp           75757 non-null  int64
 11  february_min_temp          75757 non-null  int64
 12  february_avg_temp          75757 non-null  float64
 13  february_max_temp          75757 non-null  int64
 14  march_min_temp             75757 non-null  int64
 15  march_avg_temp             75757 non-null  float64
 16  march_max_temp             75757 non-null  int64
 17  april_min_temp             75757 non-null  int64
 18  april_avg_temp             75757 non-null  float64
 19  april_max_temp             75757 non-null  int64
 20  may_min_temp               75757 non-null  int64
 21  may_avg_temp               75757 non-null  float64
 22  may_max_temp               75757 non-null  int64
 23  june_min_temp              75757 non-null  int64
 24  june_avg_temp              75757 non-null  float64
 25  june_max_temp              75757 non-null  int64
 26  july_min_temp              75757 non-null  int64
 27  july_avg_temp              75757 non-null  float64
 28  july_max_temp              75757 non-null  int64
 29  august_min_temp            75757 non-null  int64
 30  august_avg_temp            75757 non-null  float64
 31  august_max_temp            75757 non-null  int64
 32  september_min_temp         75757 non-null  int64
 33  september_avg_temp         75757 non-null  float64
 34  september_max_temp         75757 non-null  int64
 35  october_min_temp           75757 non-null  int64
 36  october_avg_temp           75757 non-null  float64
 37  october_max_temp           75757 non-null  int64
 38  november_min_temp          75757 non-null  int64
 39  november_avg_temp          75757 non-null  float64
 40  november_max_temp          75757 non-null  int64
 41  december_min_temp          75757 non-null  int64
 42  december_avg_temp          75757 non-null  float64
 43  december_max_temp          75757 non-null  int64
 44  cooling_degree_days        75757 non-null  int64
 45  heating_degree_days        75757 non-null  int64
 46  precipitation_inches       75757 non-null  float64
 47  snowfall_inches            75757 non-null  float64
 48  snowdepth_inches           75757 non-null  int64
 49  avg_temp                   75757 non-null  float64
 50  days_below_30F             75757 non-null  int64
 51  days_below_20F             75757 non-null  int64
 52  days_below_10F             75757 non-null  int64
 53  days_below_0F              75757 non-null  int64
 54  days_above_80F             75757 non-null  int64
 55  days_above_90F             75757 non-null  int64
 56  days_above_100F            75757 non-null  int64
 57  days_above_110F            75757 non-null  int64
 58  direction_max_wind_speed   34675 non-null  float64
 59  direction_peak_wind_speed  33946 non-null  float64
 60  max_wind_speed             34675 non-null  float64
 61  days_with_fog              29961 non-null  float64
 62  site_eui                   75757 non-null  float64
 63  id                         75757 non-null  int64
dtypes: float64(24), int64(37), object(3)
memory usage: 37.0+ MB

In [6]:
pd.set_option('display.max_rows',None)

In [7]:
climatedata.describe().T

,count,mean,std,min,25%,50%,75%,max
Year_Factor,75757.0,4.367755,1.471441,1.000000,3.000000,5.000000,6.000000,6.000000e+00
floor_area,75757.0,165983.865858,246875.790940,943.000000,62379.000000,91367.000000,166000.000000,6.385382e+06
year_built,73920.0,1952.306764,37.053619,0.000000,1927.000000,1951.000000,1977.000000,2.015000e+03
energy_star_rating,49048.0,61.048605,28.663683,0.000000,40.000000,67.000000,85.000000,1.000000e+02
ELEVATION,75757.0,39.506323,60.656596,-6.400000,11.900000,25.000000,42.700000,1.924500e+03
january_min_temp,75757.0,11.432343,9.381027,-19.000000,6.000000,11.000000,13.000000,4.900000e+01
january_avg_temp,75757.0,34.310468,6.996108,10.806452,29.827586,34.451613,37.322581,6.475806e+01
january_max_temp,75757.0,59.054952,5.355458,42.000000,56.000000,59.000000,62.000000,9.100000e+01
february_min_temp,75757.0,11.720567,12.577272,-13.000000,2.000000,9.000000,20.000000,4.800000e+01
february_avg_temp,75757.0,35.526837,8.866697,13.250000,31.625000,34.107143,40.879310,6.510714e+01
february_max_temp,75757.0,58.486278,8.414611,38.000000,55.000000,61.000000,62.000000,8.900000e+01
march_min_temp,75757.0,21.606281,10.004303,-9.000000,13.000000,25.000000,27.000000,5.200000e+01
march_avg_temp,75757.0,44.469292,6.657142,25.854839,38.096774,44.516129,49.354839,6.975806e+01
march_max_temp,75757.0,70.897831,7.680982,53.000000,62.000000,71.000000,78.000000,9.500000e+01
april_min_temp,75757.0,32.037171,5.577279,15.000000,26.000000,32.000000,37.000000,5.200000e+01
april_avg_temp,75757.0,53.784863,2.500473,40.280000,52.333333,53.333333,54.766667,7.450000e+01
april_max_temp,75757.0,82.661932,4.101028,62.000000,80.000000,82.000000,87.000000,1.040000e+02
may_min_temp,75757.0,44.706179,4.200319,23.000000,42.000000,45.000000,49.000000,5.800000e+01
may_avg_temp,75757.0,63.742547,2.792919,46.950000,62.790323,62.887097,65.096774,8.211290e+01
may_max_temp,75757.0,88.987856,2.864669,64.000000,88.000000,89.000000,91.000000,1.120000e+02
june_min_temp,75757.0,51.131763,3.415926,30.000000,50.000000,52.000000,53.000000,6.800000e+01
june_avg_temp,75757.0,71.066384,2.861681,54.100000,70.983333,72.250000,72.450000,8.955000e+01
june_max_temp,75757.0,91.400280,3.604068,67.000000,89.000000,90.000000,94.000000,1.190000e+02
july_min_temp,75757.0,60.571604,4.177109,37.000000,57.000000,63.000000,63.000000,7.400000e+01
july_avg_temp,75757.0,76.596879,4.090275,54.822581,76.145161,78.677419,78.790323,9.443548e+01
july_max_temp,75757.0,95.543950,4.157118,65.000000,95.000000,96.000000,98.000000,1.170000e+02
august_min_temp,75757.0,58.515068,4.441992,31.000000,57.000000,61.000000,61.000000,7.700000e+01
august_avg_temp,75757.0,75.348749,3.818895,56.693548,74.516129,75.725806,78.967742,9.490323e+01
august_max_temp,75757.0,92.572581,4.139685,66.000000,90.000000,91.000000,95.000000,1.160000e+02
september_min_temp,75757.0,50.791689,4.290884,26.000000,47.000000,52.000000,54.000000,6.500000e+01
september_avg_temp,75757.0,69.597545,3.603773,53.600000,68.200000,69.733333,71.800000,9.011667e+01
september_max_temp,75757.0,92.171139,5.011708,64.000000,91.000000,92.000000,96.000000,1.110000e+02
october_min_temp,75757.0,38.210911,5.093899,18.000000,35.000000,38.000000,40.000000,6.100000e+01
october_avg_temp,75757.0,58.727038,2.641300,44.693548,58.048387,58.758065,59.629032,8.074194e+01
october_max_temp,75757.0,81.135671,5.579513,59.000000,78.000000,80.000000,85.000000,1.080000e+02
november_min_temp,75757.0,28.630397,7.153244,4.000000,23.000000,31.000000,34.000000,5.200000e+01
november_avg_temp,75757.0,48.123133,4.094207,30.766667,45.250000,47.116667,51.339286,6.741667e+01
november_max_temp,75757.0,71.202397,4.373374,53.000000,69.000000,72.000000,74.000000,9.600000e+01
december_min_temp,75757.0,22.736777,9.014047,-16.000000,17.000000,24.000000,28.000000,4.400000e+01
december_avg_temp,75757.0,41.625569,5.869386,23.790323,38.532258,40.516129,43.435484,6.179032e+01
december_max_temp,75757.0,64.496852,6.054104,42.000000,60.000000,65.000000,71.000000,8.600000e+01
cooling_degree_days,75757.0,1202.250446,391.561780,0.000000,1128.000000,1277.000000,1489.000000,4.948000e+03
heating_degree_days,75757.0,4324.957390,824.366727,398.000000,3978.000000,4337.000000,4670.000000,7.929000e+03
precipitation_inches,75757.0,42.430651,10.592205,0.000000,39.350000,42.170000,46.320000,1.076900e+02
snowfall_inches,75757.0,29.136379,17.810894,0.000000,9.600000,31.600000,49.100000,1.273000e+02
snowdepth_inches,75757.0,164.862455,175.275869,0.000000,10.000000,101.000000,377.000000,1.292000e+03
avg_temp,75757.0,56.176705,2.241940,44.512329,55.147541,56.835616,57.215847,7.724521e+01
days_below_30F,75757.0,48.756511,27.587124,0.000000,22.000000,50.000000,66.000000,1.700000e+02
days_below_20F,75757.0,17.447932,14.469435,0.000000,5.000000,11.000000,26.000000,9.300000e+01
days_below_10F,75757.0,4.886532,7.071221,0.000000,0.000000,2.000000,7.000000,5.900000e+01
days_below_0F,75757.0,0.876764,2.894244,0.000000,0.000000,0.000000,0.000000,3.100000e+01
days_above_80F,75757.0,82.709809,25.282913,0.000000,72.000000,84.000000,97.000000,2.600000e+02
days_above_90F,75757.0,14.058701,10.943996,0.000000,6.000000,12.000000,17.000000,1.850000e+02
days_above_100F,75757.0,0.279539,2.252323,0.000000,0.000000,0.000000,0.000000,1.190000e+02
days_above_110F,75757.0,0.002442,0.142140,0.000000,0.000000,0.000000,0.000000,1.600000e+01
direction_max_wind_speed,34675.0,66.552675,131.147834,1.000000,1.000000,1.000000,1.000000,3.600000e+02
direction_peak_wind_speed,33946.0,62.779974,130.308106,1.000000,1.000000,1.000000,1.000000,3.600000e+02
max_wind_speed,34675.0,4.190601,6.458789,1.000000,1.000000,1.000000,1.000000,2.330000e+01
days_with_fog,29961.0,109.142051,50.699751,12.000000,88.000000,104.000000,131.000000,3.110000e+02
site_eui,75757.0,82.584693,58.255403,1.001169,54.528601,75.293716,97.277534,9.978661e+02
id,75757.0,37878.000000,21869.306509,0.000000,18939.000000,37878.000000,56817.000000,7.575600e+04

# Convert Year Factor

In [8]:
climatedata['Year_Factor'] = climatedata['Year_Factor'].astype('str')

# Fix Year Built

In [9]:
climatedata['year_built'] = climatedata['year_built'].replace(0,np.nan)

In [10]:
climatedata.dropna(subset={'year_built'},axis=0,inplace=True)

In [11]:
climatedata['age'] = datetime.date.today().year - climatedata['year_built']

# Drop Unnecessary Columns

In [12]:
climatedata.drop(['id','year_built'],axis=1,inplace=True)

In [13]:
climatedata['age'] = climatedata['age'].astype('int64')

In [14]:
climatedata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73914 entries, 0 to 75756
Data columns (total 63 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year_Factor                73914 non-null  object
 1   State_Factor               73914 non-null  object
 2   building_class             73914 non-null  object
 3   facility_type              73914 non-null  object
 4   floor_area                 73914 non-null  float64
 5   energy_star_rating         48439 non-null  float64
 6   ELEVATION                  73914 non-null  float64
 7   january_min_temp           73914 non-null  int64
 8   january_avg_temp           73914 non-null  float64
 9   january_max_temp           73914 non-null  int64
 10  february_min_temp          73914 non-null  int64
 11  february_avg_temp          73914 non-null  float64
 12  february_max_temp          73914 non-null  int64
 13  march_min_temp             73914 non-null  int64
 14  march_avg_temp             73914 non-null  float64
 15  march_max_temp             73914 non-null  int64
 16  april_min_temp             73914 non-null  int64
 17  april_avg_temp             73914 non-null  float64
 18  april_max_temp             73914 non-null  int64
 19  may_min_temp               73914 non-null  int64
 20  may_avg_temp               73914 non-null  float64
 21  may_max_temp               73914 non-null  int64
 22  june_min_temp              73914 non-null  int64
 23  june_avg_temp              73914 non-null  float64
 24  june_max_temp              73914 non-null  int64
 25  july_min_temp              73914 non-null  int64
 26  july_avg_temp              73914 non-null  float64
 27  july_max_temp              73914 non-null  int64
 28  august_min_temp            73914 non-null  int64
 29  august_avg_temp            73914 non-null  float64
 30  august_max_temp            73914 non-null  int64
 31  september_min_temp         73914 non-null  int64
 32  september_avg_temp         73914 non-null  float64
 33  september_max_temp         73914 non-null  int64
 34  october_min_temp           73914 non-null  int64
 35  october_avg_temp           73914 non-null  float64
 36  october_max_temp           73914 non-null  int64
 37  november_min_temp          73914 non-null  int64
 38  november_avg_temp          73914 non-null  float64
 39  november_max_temp          73914 non-null  int64
 40  december_min_temp          73914 non-null  int64
 41  december_avg_temp          73914 non-null  float64
 42  december_max_temp          73914 non-null  int64
 43  cooling_degree_days        73914 non-null  int64
 44  heating_degree_days        73914 non-null  int64
 45  precipitation_inches       73914 non-null  float64
 46  snowfall_inches            73914 non-null  float64
 47  snowdepth_inches           73914 non-null  int64
 48  avg_temp                   73914 non-null  float64
 49  days_below_30F             73914 non-null  int64
 50  days_below_20F             73914 non-null  int64
 51  days_below_10F             73914 non-null  int64
 52  days_below_0F              73914 non-null  int64
 53  days_above_80F             73914 non-null  int64
 54  days_above_90F             73914 non-null  int64
 55  days_above_100F            73914 non-null  int64
 56  days_above_110F            73914 non-null  int64
 57  direction_max_wind_speed   33916 non-null  float64
 58  direction_peak_wind_speed  33212 non-null  float64
 59  max_wind_speed             33916 non-null  float64
 60  days_with_fog              29399 non-null  float64
 61  site_eui                   73914 non-null  float64
 62  age                        73914 non-null  int64
dtypes: float64(23), int64(36), object(4)
memory usage: 36.1+ MB

In [15]:
climatedata['Q1'] = climatedata.loc[:,['january_avg_temp','february_avg_temp','march_avg_temp']].mean(axis=1)
climatedata['Q2'] = climatedata.loc[:,['april_avg_temp','may_avg_temp','june_avg_temp']].mean(axis=1)
climatedata['Q3'] = climatedata.loc[:,['july_avg_temp','august_avg_temp','september_avg_temp']].mean(axis=1)
climatedata['Q4'] = climatedata.loc[:,['october_avg_temp','november_avg_temp','december_avg_temp']].mean(axis=1)

In [16]:
climatedata.drop(['january_avg_temp','february_avg_temp','march_avg_temp','january_min_temp','february_min_temp','march_min_temp','january_max_temp','february_max_temp','march_max_temp',
                    'april_avg_temp','may_avg_temp','june_avg_temp','april_min_temp','may_min_temp','june_min_temp','april_max_temp','may_max_temp','june_max_temp',
                    'july_avg_temp','august_avg_temp','september_avg_temp','july_min_temp','august_min_temp','september_min_temp','july_max_temp','august_max_temp','september_max_temp',
                    'october_avg_temp','november_avg_temp','december_avg_temp','october_min_temp','november_min_temp','december_min_temp','october_max_temp','november_max_temp','december_max_temp'],axis=1,inplace=True)

In [17]:
climatedata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73914 entries, 0 to 75756
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year_Factor                73914 non-null  object
 1   State_Factor               73914 non-null  object
 2   building_class             73914 non-null  object
 3   facility_type              73914 non-null  object
 4   floor_area                 73914 non-null  float64
 5   energy_star_rating         48439 non-null  float64
 6   ELEVATION                  73914 non-null  float64
 7   cooling_degree_days        73914 non-null  int64
 8   heating_degree_days        73914 non-null  int64
 9   precipitation_inches       73914 non-null  float64
 10  snowfall_inches            73914 non-null  float64
 11  snowdepth_inches           73914 non-null  int64
 12  avg_temp                   73914 non-null  float64
 13  days_below_30F             73914 non-null  int64
 14  days_below_20F             73914 non-null  int64
 15  days_below_10F             73914 non-null  int64
 16  days_below_0F              73914 non-null  int64
 17  days_above_80F             73914 non-null  int64
 18  days_above_90F             73914 non-null  int64
 19  days_above_100F            73914 non-null  int64
 20  days_above_110F            73914 non-null  int64
 21  direction_max_wind_speed   33916 non-null  float64
 22  direction_peak_wind_speed  33212 non-null  float64
 23  max_wind_speed             33916 non-null  float64
 24  days_with_fog              29399 non-null  float64
 25  site_eui                   73914 non-null  float64
 26  age                        73914 non-null  int64
 27  Q1                         73914 non-null  float64
 28  Q2                         73914 non-null  float64
 29  Q3                         73914 non-null  float64
 30  Q4                         73914 non-null  float64
dtypes: float64(15), int64(12), object(4)
memory usage: 18.0+ MB

# group facility_type

In [18]:
climatedata[['Year_Factor','State_Factor','building_class','facility_type']] = climatedata[['Year_Factor','State_Factor','building_class','facility_type']].astype('category')
facility = ['Commercial','Education','Food','Health','Industrial','Lodging','Multifamily','Office','Public_Assembly','Public_Safety','Retail','Service','Warehouse']
facility1 = ['Parking','Laboratory','Nursing','Building','Data','Religious']
categorytype = ['Commercial','Education','Food','Health','Industry','Lodging','Multifamily','Office','Public_area','Public_safety','Retail','Service','Warehouse']
categorytype1 = ['Commercial','Health','Lodging','Multifamily','Office','Public_area']
for i, j in zip(facility,categorytype):
    climatedata.loc[climatedata['facility_type'].str.contains(i,case=False), 'facility_type_1'] = j
for i1, j1 in zip(facility1,categorytype1):
    climatedata.loc[climatedata['facility_type'].str.contains(i1,case=False), 'facility_type_1'] = j1
climatedata.fillna({'facility_type_1':'Multifamily'},inplace=True)
climatedata.drop('facility_type',axis=1,inplace=True)
climatedata.rename(columns={'facility_type_1':'facility_type'},inplace=True)

In [19]:
climatedata['facility_type'].value_counts()

Multifamily      42245
Office           12908
Education         5040
Lodging           3504
Commercial        2908
Warehouse         2807
Retail            1384
Public_area       1052
Health             623
Food               503
Industry           380
Service            307
Public_safety      253
Name: facility_type, dtype: int64

In [20]:
y = climatedata['site_eui'].copy()
x = climatedata.drop('site_eui',axis=1).copy()

In [21]:
x['facility_type'] = x['facility_type'].astype('category')

In [22]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73914 entries, 0 to 75756
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year_Factor                73914 non-null  category
 1   State_Factor               73914 non-null  category
 2   building_class             73914 non-null  category
 3   floor_area                 73914 non-null  float64
 4   energy_star_rating         48439 non-null  float64
 5   ELEVATION                  73914 non-null  float64
 6   cooling_degree_days        73914 non-null  int64
 7   heating_degree_days        73914 non-null  int64
 8   precipitation_inches       73914 non-null  float64
 9   snowfall_inches            73914 non-null  float64
 10  snowdepth_inches           73914 non-null  int64
 11  avg_temp                   73914 non-null  float64
 12  days_below_30F             73914 non-null  int64
 13  days_below_20F             73914 non-null  int64
 14  days_below_10F             73914 non-null  int64
 15  days_below_0F              73914 non-null  int64
 16  days_above_80F             73914 non-null  int64
 17  days_above_90F             73914 non-null  int64
 18  days_above_100F            73914 non-null  int64
 19  days_above_110F            73914 non-null  int64
 20  direction_max_wind_speed   33916 non-null  float64
 21  direction_peak_wind_speed  33212 non-null  float64
 22  max_wind_speed             33916 non-null  float64
 23  days_with_fog              29399 non-null  float64
 24  age                        73914 non-null  int64
 25  Q1                         73914 non-null  float64
 26  Q2                         73914 non-null  float64
 27  Q3                         73914 non-null  float64
 28  Q4                         73914 non-null  float64
 29  facility_type              73914 non-null  category
dtypes: category(4), float64(14), int64(12)
memory usage: 15.5 MB

# Split Data

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.15,random_state=42)
print(len(x_train),'x_train, ',len(x_test),'x_test, ', len(y_train),'y_train, ', len(y_test),'y_test')

62826 x_train,  11088 x_test,  62826 y_train,  11088 y_test

In [24]:
x_train, x_valid, y_train, y_valid = train_test_split(x_train,y_train,test_size=0.15,random_state=42)
print(len(x_train),'x_train, ',len(x_test),'x_valid, ', len(y_train),'y_train, ', len(y_test),'y_valid')

53402 x_train,  11088 x_valid,  53402 y_train,  11088 y_valid

In [25]:
x_train.shape

(53402, 30)

# Get ready for Scaling and encoding

In [26]:
categories = x_train.select_dtypes('category').columns.tolist()
numerical = x_train.select_dtypes('number').columns.tolist()

In [27]:
for i in ['direction_max_wind_speed','direction_peak_wind_speed','max_wind_speed']:
    numerical.remove(i)

In [28]:
numerical

['floor_area',
 'energy_star_rating',
 'ELEVATION',
 'cooling_degree_days',
 'heating_degree_days',
 'precipitation_inches',
 'snowfall_inches',
 'snowdepth_inches',
 'avg_temp',
 'days_below_30F',
 'days_below_20F',
 'days_below_10F',
 'days_below_0F',
 'days_above_80F',
 'days_above_90F',
 'days_above_100F',
 'days_above_110F',
 'days_with_fog',
 'age',
 'Q1',
 'Q2',
 'Q3',
 'Q4']

In [29]:
simplenumerical = ['direction_max_wind_speed','direction_peak_wind_speed','max_wind_speed']

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PowerTransformer
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector as selector

In [31]:
simple_pipe = Pipeline(steps=[("simpleimpute", SimpleImputer(missing_values=np.nan,strategy='mean')),("scale",PowerTransformer())])
knn_pipe = Pipeline(steps=[("knnimpute", KNNImputer(n_neighbors=5)),("scale",PowerTransformer())])
cat_pipe = OneHotEncoder(handle_unknown="ignore")

preprocessor = ColumnTransformer(transformers=[("nums",simple_pipe,simplenumerical),
                                                ("numk",knn_pipe,numerical)
                                                ])

preprocessor.fit(x_train)

c:\Python39\lib\site-packages\sklearn\preprocessing\_data.py:3251: RuntimeWarning: divide by zero encountered in log
  loglike = -n_samples / 2 * np.log(x_trans.var())

ColumnTransformer(transformers=[('nums',
                                 Pipeline(steps=[('simpleimpute',
                                                  SimpleImputer()),
                                                 ('scale',
                                                  PowerTransformer())]),
                                 ['direction_max_wind_speed',
                                  'direction_peak_wind_speed',
                                  'max_wind_speed']),
                                ('numk',
                                 Pipeline(steps=[('knnimpute', KNNImputer()),
                                                 ('scale',
                                                  PowerTransformer())]),
                                 ['floor_area', 'energy_star_rating',
                                  'ELEVATION', 'cooling_degree_days',
                                  'heating_degree_days', 'precipitation_inches',
                                  'snowfall_inches', 'snowdepth_inches',
                                  'avg_temp', 'days_below_30F',
                                  'days_below_20F', 'days_below_10F',
                                  'days_below_0F', 'days_above_80F',
                                  'days_above_90F', 'days_above_100F',
                                  'days_above_110F', 'days_with_fog', 'age',
                                  'Q1', 'Q2', 'Q3', 'Q4'])])

In [32]:
preprocessor_cat = ColumnTransformer(transformers=[("cat",cat_pipe,categories)
                                                ])
preprocessor_cat.fit(x_train)

ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Year_Factor', 'State_Factor',
                                  'building_class', 'facility_type'])])

In [33]:
cat_column = (preprocessor_cat.get_feature_names_out()).tolist()

In [34]:
simplenumerical.extend(numerical)

In [35]:
from sklearn import set_config

set_config(display="diagram")
preprocessor

ColumnTransformer(transformers=[('nums',
                                 Pipeline(steps=[('simpleimpute',
                                                  SimpleImputer()),
                                                 ('scale',
                                                  PowerTransformer())]),
                                 ['direction_max_wind_speed',
                                  'direction_peak_wind_speed', 'max_wind_speed',
                                  'floor_area', 'energy_star_rating',
                                  'ELEVATION', 'cooling_degree_days',
                                  'heating_degree_days', 'precipitation_inches',
                                  'snowfall_inches', 'snowdepth_inches',
                                  'avg_te...
                                                  PowerTransformer())]),
                                 ['floor_area', 'energy_star_rating',
                                  'ELEVATION', 'cooling_degree_days',
                                  'heating_degree_days', 'precipitation_inches',
                                  'snowfall_inches', 'snowdepth_inches',
                                  'avg_temp', 'days_below_30F',
                                  'days_below_20F', 'days_below_10F',
                                  'days_below_0F', 'days_above_80F',
                                  'days_above_90F', 'days_above_100F',
                                  'days_above_110F', 'days_with_fog', 'age',
                                  'Q1', 'Q2', 'Q3', 'Q4'])])

In [36]:
def transform(df,df1,df2):
    num_transform = df.transform(df2)
    num_processed = pd.DataFrame(num_transform,columns = simplenumerical)
    cat_transform = df1.transform(df2)
    cat_processed = pd.DataFrame(cat_transform.toarray(),columns = cat_column)
    baseline_processed = pd.concat([num_processed,cat_processed],axis=1)
    return baseline_processed

In [37]:
train_data = transform(preprocessor,preprocessor_cat,x_train)
valid_data = transform(preprocessor,preprocessor_cat,x_valid)
test_data = transform(preprocessor,preprocessor_cat,x_test)

In [38]:
train_data.to_parquet('x_train_knn_simple.parquet')
valid_data.to_parquet('x_valid_knn_simple.parquet')
test_data.to_parquet('x_test_knn_simple.parquet')

In [39]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53402 entries, 0 to 53401
Data columns (total 54 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   direction_max_wind_speed          53402 non-null  float64
 1   direction_peak_wind_speed         53402 non-null  float64
 2   max_wind_speed                    53402 non-null  float64
 3   floor_area                        53402 non-null  float64
 4   energy_star_rating                53402 non-null  float64
 5   ELEVATION                         53402 non-null  float64
 6   cooling_degree_days               53402 non-null  float64
 7   heating_degree_days               53402 non-null  float64
 8   precipitation_inches              53402 non-null  float64
 9   snowfall_inches                   53402 non-null  float64
 10  snowdepth_inches                  53402 non-null  float64
 11  avg_temp                          53402 non-null  float64
 12  days_below_30F                    53402 non-null  float64
 13  days_below_20F                    53402 non-null  float64
 14  days_below_10F                    53402 non-null  float64
 15  days_below_0F                     53402 non-null  float64
 16  days_above_80F                    53402 non-null  float64
 17  days_above_90F                    53402 non-null  float64
 18  days_above_100F                   53402 non-null  float64
 19  days_above_110F                   53402 non-null  float64
 20  days_with_fog                     53402 non-null  float64
 21  age                               53402 non-null  float64
 22  Q1                                53402 non-null  float64
 23  Q2                                53402 non-null  float64
 24  Q3                                53402 non-null  float64
 25  Q4                                53402 non-null  float64
 26  cat__Year_Factor_1                53402 non-null  float64
 27  cat__Year_Factor_2                53402 non-null  float64
 28  cat__Year_Factor_3                53402 non-null  float64
 29  cat__Year_Factor_4                53402 non-null  float64
 30  cat__Year_Factor_5                53402 non-null  float64
 31  cat__Year_Factor_6                53402 non-null  float64
 32  cat__State_Factor_State_1         53402 non-null  float64
 33  cat__State_Factor_State_10        53402 non-null  float64
 34  cat__State_Factor_State_11        53402 non-null  float64
 35  cat__State_Factor_State_2         53402 non-null  float64
 36  cat__State_Factor_State_4         53402 non-null  float64
 37  cat__State_Factor_State_6         53402 non-null  float64
 38  cat__State_Factor_State_8         53402 non-null  float64
 39  cat__building_class_Commercial    53402 non-null  float64
 40  cat__building_class_Residential   53402 non-null  float64
 41  cat__facility_type_Commercial     53402 non-null  float64
 42  cat__facility_type_Education      53402 non-null  float64
 43  cat__facility_type_Food           53402 non-null  float64
 44  cat__facility_type_Health         53402 non-null  float64
 45  cat__facility_type_Industry       53402 non-null  float64
 46  cat__facility_type_Lodging        53402 non-null  float64
 47  cat__facility_type_Multifamily    53402 non-null  float64
 48  cat__facility_type_Office         53402 non-null  float64
 49  cat__facility_type_Public_area    53402 non-null  float64
 50  cat__facility_type_Public_safety  53402 non-null  float64
 51  cat__facility_type_Retail         53402 non-null  float64
 52  cat__facility_type_Service        53402 non-null  float64
 53  cat__facility_type_Warehouse      53402 non-null  float64
dtypes: float64(54)
memory usage: 22.0 MB

In [40]:
scalor = StandardScaler()

In [41]:
y_train = pd.DataFrame(y_train)
y_valid = pd.DataFrame(y_valid)
y_test = pd.DataFrame(y_test)

In [42]:
train_data.head()

,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,floor_area,energy_star_rating,ELEVATION,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,...,cat__facility_type_Health,cat__facility_type_Industry,cat__facility_type_Lodging,cat__facility_type_Multifamily,cat__facility_type_Office,cat__facility_type_Public_area,cat__facility_type_Public_safety,cat__facility_type_Retail,cat__facility_type_Service,cat__facility_type_Warehouse
0,1.788841,1.834377,1.906874,-0.845773,1.564069,-1.462041,1.274025,0.063348,-0.245942,1.062769,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,-1.247618,-1.246910,-1.211105,-0.407408,-1.715388,0.638874,-0.482827,0.664602,1.178596,1.106299,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.713874,1.785228,1.927146,1.404817,0.765090,2.010308,-1.380041,2.945302,-0.164680,0.852802,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.247618,-1.246910,-1.211105,1.218170,-0.365523,-1.462041,0.858183,-0.220167,-0.120621,0.411490,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-1.247618,-1.246910,-1.211105,-0.738009,-0.923363,0.638874,-0.482827,0.664602,1.178596,1.106299,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
scalor.fit(y_train)
scaled_y_train_simple = pd.DataFrame(scalor.transform(y_train),columns=['site_eui'])

In [44]:
scaled_y_valid_simple = pd.DataFrame(scalor.transform(y_valid),columns=['site_eui'])
scaled_y_test_simple = pd.DataFrame(scalor.transform(y_test),columns=['site_eui'])

In [45]:
scaled_y_train_simple.to_parquet('scaled_y_train_knn.parquet')
scaled_y_valid_simple.to_parquet('scaled_y_valid_knn.parquet')
scaled_y_test_simple.to_parquet('scaled_y_test_knn.parquet')

In [46]:
# baseline_preprocessed = preprocessor.transform(x_train)

# # create a dataframe from the output array
# baseline_preprocessed = pd.DataFrame(
#     baseline_preprocessed,)

In [47]:
# baseline_preprocessed.head()

In [48]:
# baseline_preprocessed.to_parquet('x_train.parquet')